name: deployer
on:
  pull_request_target:
    types:
      - closed
env:
  QUATERNION: ${{secrets.QAK}}
  QLOCATION: ${{secrets.QCOOR}}

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    
    - name: checkout main    
      uses: actions/checkout@v3
      with:
        ref: main 
    
    - name: generate server access
      run: |
          echo "$QUATERNION" >> $HOME/qak.pem
          chmod 400 $HOME/qak.pem

    - name: entity deployer
      run: |
        ls -lh $HOME/qak.pem
        echo $USER
        sudo chown root:root $HOME/qak.pem
        sudo chown root:root $HOME
        ls -lh $HOME/qak.pem
        ls -lh $HOME
        scp -i $HOME/qak.pem -o StrictHostKeyChecking=no decoy.py $QLOCATION:~/
