name: deployer
on:
  pull_request_target:
    types:
      - closed
env:
  QUATERNION: ${{secrets.QAK}}
  QLOCATION: ${{secrets.QCOOR}}

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    
    - name: checkout main    
      uses: actions/checkout@v3
      with:
        ref: main 
    
    - name: generate server access
      run: |
          mkdir .quaternion
          echo "$QUATERNION" >> .quaternion/qak.pem
          chmod 400 .quaternion/qak.pem

    - name: entity deployer
      run: |
        ls -lh .quaternion/qak.pem
        echo $USER
        sudo chown $USER:$USER .quaternion/qak.pem
        sudo chown $USER:$USER .quaternion
        ls -lh 
        ls -lh .quaternion
        scp -i .quaternion/qak.pem -o StrictHostKeyChecking=no decoy.py $QLOCATION:~/
