name: deployer
on:
  pull_request_target:
    types:
      - closed
env:
  QUATERNION: ${{secrets.QAK}}
  QLOCATION: ${{secrets.QCOOR}}

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    
    - name: checkout main    
      uses: actions/checkout@v3
      with:
        ref: main 
    
    - name: generate server access
      run: |
          mkdir .ssh
          echo "$QUATERNION" >> .ssh/qak.pem
          chmod 400 .ssh/qak.pem
    - name: check fs
      run: |
          ssh-agent
          echo $SSH_AUTH_SOCK
          ssh-keyscan -H github.com >> .ssh/known_hosts
          cat .ssh/know_hosts
          
    - name: entity deployer
      run: |
        ls -lh .ssh/qak.pem
        sudo chown -R $USER:$USER .ssh
        ls -Rlh .ssh
        scp -v -i .ssh/qak.pem -o StrictHostKeyChecking=no decoy.py $QLOCATION:~/
