name: deployer
on:
  pull_request_target:
    types:
      - closed
env:
  QUATERNION: ${{secrets.QAK}}
  QLOCATION: ${{secrets.QCOOR}}

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    
    - name: checkout main    
      uses: actions/checkout@v3
      with:
        ref: main 
    
    - name: generate server access
      run: |
          mkdir .ssh
          mkdir -p ~/.ssh
          touch ~/.ssh/identity
          touch ~/.ssh/config
          echo "$QUATERNION" >> .ssh/qak.pem
          echo "$QUATERNION" >> ~/.ssh/identity
          chmod 400 .ssh/qak.pem
          find / -iname .docker*
          
    - name: check fs
      run: |
          echo "SSH_AUTH_SOCK -> "$SSH_AUTH_SOCK
          eval `ssh-agent -s`
          ssh-add
          ssh-add -l
          '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts          
          cat ~/.ssh/known_hosts
          pwd
          
    - name: entity deployer
      run: |
        ls -lh .ssh/qak.pem
        sudo chown -R $USER:$USER .ssh
        ls -Rlh .ssh
        scp -v -i .ssh/qak.pem -o StrictHostKeyChecking=no decoy.py $QLOCATION:~/
