name: deployer
on:
  pull_request_target:
    types:
      - closed
env:
  QUATERNION: ${{secrets.QPAK}}
  QLOCATION: ${{secrets.QCOOR}}

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    
    - name: checkout main    
      uses: actions/checkout@v4
      with:
        ref: main 
    
    - name: generate server access
      run: |
          mkdir .ssh
          echo "$QUATERNION" >> .ssh/qak.pem
          chmod 400 .ssh/qak.pem       
          
    - name: entity deployer
      run: |
        sudo chown -R $USER:$USER .ssh
        scp -i .ssh/qak.pem -o StrictHostKeyChecking=no decoy.py $QLOCATION:~/
