name: branch-scanner 
on: [push]

env:
  STK: ${{secrets.XTOKEN}}
  CBRANCH: ${{ github.ref }}
  COWNER: ${{ github.context.repo.owner }}
  CREPO: ${{ github.context.repo.repo }}

jobs:
  analyze:
    name: scanner
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
   
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # install the python version needed

    - name: install python packages
      run: |
          python -m pip install --upgrade pip
          pip install slack-notifications
    
    - name: launch decoy
      run: |
          python decoy.py

  ci:
    needs: analyze
    name: continuous integrator
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
   
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # install the python version needed

    - name: install python packages
      run: |
          python -m pip install pip==23.3.2
          pip install slack-notifications
          pip install -U pytest
    
    - name: launch decoy
      run: |
         pytest -s 

  build:
    needs: ci 
    name: decoy
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    
    - name: checkout main    
      uses: actions/checkout@v3
      with:
        ref: main 
    
    - name: displayer
      run: echo "..........-> ........."
